/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_3;

/**
 *
 * @author Admin
 */
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextField;

public class katalog extends javax.swing.JFrame {

    /**
     * Creates new form katalog
     */
    ArrayList<CartItem> cart = new ArrayList<>();
    ArrayList<javax.swing.JLabel> qtyFields = new ArrayList<>();

    public katalog() {
        initComponents();
        setLocationRelativeTo(null); // posisi ke tengah layar
        setResizable(false);
        initProducts();

    }

    private void initProducts() {
        cart.add(new CartItem(
                new CoffeeProduct("Coffee Hitam Lampung", 11000, "Hot", false)
        ));
        cart.add(new CartItem(
                new PromoCoffee("Homemade Caramel Ice Coffee", 33000, "Ice", true, 25)
        ));
        cart.add(new CartItem(
                new CoffeeProduct("Coffee Latte", 23000, "Hot", true)
        ));
        cart.add(new CartItem(
                new CoffeeProduct("Cappuccino", 22000, "Hot", true)
        ));

        // HUBUNGKAN LABEL QTY (URUTANNYA PENTING!)
        qtyFields.add(LblHitam);     // index 0
        qtyFields.add(lblcaramel);  // index 1
        qtyFields.add(labellatte);  // index 2
        qtyFields.add(lblcino);     // index 3

        // set awal 0
        for (javax.swing.JLabel lbl : qtyFields) {
            lbl.setText("0");
        }
    }

    private void addQty(int index) {
        cart.get(index).increment();
        qtyFields.get(index)
                .setText(String.valueOf(cart.get(index).getQty()));
    }

    private void minQty(int index) {
        cart.get(index).decrement();
        qtyFields.get(index)
                .setText(String.valueOf(cart.get(index).getQty()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        plescino = new javax.swing.JButton();
        mincino = new javax.swing.JButton();
        lblcino = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LblHitam = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mincara = new javax.swing.JButton();
        plescara = new javax.swing.JButton();
        lblcaramel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pleslate = new javax.swing.JButton();
        minlate = new javax.swing.JButton();
        labellatte = new javax.swing.JLabel();
        CheckOut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 107, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Desain tanpa judul (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/coffee4.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("<html>   <div style=\"text-align:center;\"> Rp 22.000 </div> </html> ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("<html>   <div style=\"text-align:center;\"> Coffee Cappuccino</div> </html> ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        plescino.setBackground(new java.awt.Color(255, 255, 255));
        plescino.setText("+");
        plescino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plescinoActionPerformed(evt);
            }
        });
        jPanel3.add(plescino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 20));

        mincino.setBackground(new java.awt.Color(255, 255, 255));
        mincino.setText("-");
        mincino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mincinoActionPerformed(evt);
            }
        });
        jPanel3.add(mincino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        lblcino.setBackground(new java.awt.Color(0, 0, 0));
        lblcino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcino.setText("0");
        jPanel3.add(lblcino, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 200, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 160, 230));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cofee_1.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("<html>   <div style=\"text-align:center;\"> Rp 11.000 </div> </html> ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("<html>   <div style=\"text-align:center;\"> Coffee Hitam Lampung</div> </html> ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 20));

        LblHitam.setBackground(new java.awt.Color(0, 0, 0));
        LblHitam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblHitam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHitam.setText("0");
        jPanel5.add(LblHitam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 230));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/coofe2.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("<html>   <div style=\"text-align:center;\"> Rp 33.000 </div> </html> ");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("<html>   <div style=\"text-align:center;\">Homemade caramel Icde Coffee</div> </html> ");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        mincara.setBackground(new java.awt.Color(255, 255, 255));
        mincara.setText("-");
        mincara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mincaraActionPerformed(evt);
            }
        });
        jPanel6.add(mincara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        plescara.setBackground(new java.awt.Color(255, 255, 255));
        plescara.setText("+");
        plescara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plescaraActionPerformed(evt);
            }
        });
        jPanel6.add(plescara, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 20));

        lblcaramel.setBackground(new java.awt.Color(0, 0, 0));
        lblcaramel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcaramel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcaramel.setText("0");
        jPanel6.add(lblcaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 200, 60, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 230));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/coffee3.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("<html>   <div style=\"text-align:center;\"> Rp 23.000 </div> </html> ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setText("<html>   <div style=\"text-align:center;\"> Coffee Latte</div> </html> ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        pleslate.setBackground(new java.awt.Color(255, 255, 255));
        pleslate.setText("+");
        pleslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pleslateActionPerformed(evt);
            }
        });
        jPanel4.add(pleslate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 20));

        minlate.setBackground(new java.awt.Color(255, 255, 255));
        minlate.setText("-");
        minlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minlateActionPerformed(evt);
            }
        });
        jPanel4.add(minlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        labellatte.setBackground(new java.awt.Color(0, 0, 0));
        labellatte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labellatte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellatte.setText("0");
        jPanel4.add(labellatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 200, 60, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 160, 230));

        CheckOut.setBackground(new java.awt.Color(51, 255, 51));
        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckOut.setForeground(new java.awt.Color(255, 255, 255));
        CheckOut.setText("Checkout");
        CheckOut.setFocusCycleRoot(true);
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel10.setText("Popular");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/25% Sale Today!.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 770, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 460));

        jMenu1.setText("Menu Lainya");

        Laporan.setText("Masukan Saran");
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });
        jMenu1.add(Laporan);

        jMenuItem3.setText("Laporan Pesanan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        addQty(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void plescaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plescaraActionPerformed
        // TODO add your handling code here:
        addQty(1);

    }//GEN-LAST:event_plescaraActionPerformed

    private void pleslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pleslateActionPerformed
        // TODO add your handling code here:
        addQty(2);
    }//GEN-LAST:event_pleslateActionPerformed

    private void plescinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plescinoActionPerformed
        // TODO add your handling code here:
        addQty(3);
    }//GEN-LAST:event_plescinoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        minQty(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mincaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mincaraActionPerformed
        // TODO add your handling code here:
        minQty(1);
    }//GEN-LAST:event_mincaraActionPerformed

    private void minlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minlateActionPerformed
        // TODO add your handling code here:
        minQty(2);
    }//GEN-LAST:event_minlateActionPerformed

    private void mincinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mincinoActionPerformed
        // TODO add your handling code here:
        minQty(3);
    }//GEN-LAST:event_mincinoActionPerformed

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        // TODO add your handling code here:
        StringBuilder detail = new StringBuilder();
        int total = 0;

        for (CartItem item : cart) {
            if (item.getQty() > 0) {
                detail.append(item.getProductName())
                        .append(" x ")
                        .append(item.getQty())
                        .append(" = Rp ")
                        .append(item.getSubtotal())
                        .append("\n");

                total += item.getSubtotal();
            }
        }

        detail.append("\n-----------------------\n");
        detail.append("TOTAL BAYAR : Rp ").append(total);

        // PINDAH KE FORM PEMBAYARAN
        laman_pembayaran bayar = new laman_pembayaran(detail.toString());
        bayar.setVisible(true);
        this.dispose(); // tutup katalog

    }//GEN-LAST:event_CheckOutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Fitur ini belum tersedia.\nTunggu pembaruan selanjutnya!",
                "Informasi",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_LaporanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
           javax.swing.JOptionPane.showMessageDialog(
                this,
                "Fitur ini belum tersedia.\nTunggu pembaruan selanjutnya!",
                "Informasi",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(katalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(katalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(katalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(katalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new katalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOut;
    private javax.swing.JMenuItem Laporan;
    private javax.swing.JLabel LblHitam;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labellatte;
    private javax.swing.JLabel lblcaramel;
    private javax.swing.JLabel lblcino;
    private javax.swing.JButton mincara;
    private javax.swing.JButton mincino;
    private javax.swing.JButton minlate;
    private javax.swing.JButton plescara;
    private javax.swing.JButton plescino;
    private javax.swing.JButton pleslate;
    // End of variables declaration//GEN-END:variables
}
